Add support for external zsh-theme files

diff --git a/prompt/functions/prompt_omz_setup b/prompt/functions/prompt_omz_setup
--- a/prompt/functions/prompt_omz_setup
+++ b/prompt/functions/prompt_omz_setup
@@ -1,7 +1,8 @@
 ### make sure we have OMZ set up properly
 0=${${(%):-%x}}
-ZSH="${ZSH:-${0:A:h:h}/external/ohmyzsh}"
-ZSH_THEME=${ZSH_THEME:-robbyrussell}
+local ZSH="${ZSH:-${0:A:h:h}/external/ohmyzsh}"
+local ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
+local ZSH_THEME=${ZSH_THEME:-robbyrussell}
 
 ### omz theme lib dependencies
 typeset -f bzr_prompt_info > /dev/null || source "$ZSH"/lib/bzr.zsh
@@ -22,7 +23,15 @@ function work_in_progress() {
 }
 
 function {
-  [[ -f $ZSH/themes/${ZSH_THEME}.zsh-theme ]] || return 1
+  local zsh_theme
+  if [[ -f $ZSH/themes/${ZSH_THEME}.zsh-theme ]]; then
+    zsh_theme=$ZSH/themes/${ZSH_THEME}.zsh-theme
+  elif [[ -f $ZSH_CUSTOM/themes/${ZSH_THEME}.zsh-theme ]]; then
+    zsh_theme=$ZSH_CUSTOM/themes/${ZSH_THEME}.zsh-theme
+  else
+    >&2 echo "Unable to find zsh-theme '$ZSH_THEME'"
+    return 1
+  fi
 
   # themes are bad at reseting themselves, so let's help out by resetting to
   # defaults before applying a new theme
@@ -39,5 +48,5 @@ function {
   RPS1=''
 
   # set the theme
-  source $ZSH/themes/$ZSH_THEME.zsh-theme
+  source $zsh_theme
 }
